### PR TITLE
chore(project): fix d.ts

### LINKED ISSUE #279: Wrong return type for authService.client property
The property is declared as follows:

```
  /**
   * Getter: The configured client for all aurelia-authentication requests
   *
   * @return {HttpClient}
   */
  get client(): HttpClient {
    return this.config.client;
  }
```

But it's wrong, the type is `Rest`.

### LINKED ISSUE #280: Wrong type for authService.config property
It is defined as follows:

```
  /**
   * The Config instance that contains the current configuration setting
   *
   * @param  {Config}
   */
  config: Config;
```

But it should be `BaseConfig`, not `Config` as it points to the definition in `aurelia-api.d.ts`

### PR DESCRIPTION
**Pull request by pfurini**
This resolves #279 and resolves #280

### CODE REVIEW

**Review by RWOverdijk — APPROVED** [review]

File: src/authService.js [hunk 1]
```diff
@@ -112,9 +112,9 @@ export class AuthService {
   /**
    * Getter: The configured client for all aurelia-authentication requests
    *
-   * @return {HttpClient}
+   * @return {Rest}
    */
-  get client(): HttpClient {
+  get client(): Rest {
```
Comment (doktordirk) [inline src/authService.js:118]: better gets (the previously missing) import Rest at top i recon

**Review by doktordirk — CHANGES_REQUESTED** [review]

File: src/authService.js (hunk 1 above)
Comment (doktordirk) [reply src/authService.js:118]: oh and only ./src please

Comment (pfurini) [reply src/authService.js:118]: Is it ok now?

**Review by doktordirk — APPROVED** [review]
