### PR TITLE
More consistent redirectUrl overwrite 

### LINKED ISSUE #294: Typings for authenticate method are incorrect
The documentation states the authenticate method has three parameters, the second of which is as follows:
`[redirectUri]  [string/0/null/undef ]  redirectUri overwrite. 0=off, null/undef=use default`
However the typing information just describes it as a string parameter.

I would suggest keep it as a string and just use an empty string, "", instead of 0, to indicate not a desire to not redirect anywhere.  Then it is simply an option string property...
- Not present = use default
- Present but empty = do not redirect
- Present = redirect to value supplied

### PR DESCRIPTION
**Pull request by doktordirk**
Options to not redirect changed from 0 to '' for consistency and ease of use

@nexbit if i deprecate 0 in favor of '' and keep the dts, is that a breaking change? for js users it isn't, but for ts? but then, they had to use string anyways, so i guess it's not breaking? but could a previous used '' (which now doesn't redirect) be breaking. i guess so, question is, whether anyone had used it like that

closes https://github.com/SpoonX/aurelia-authentication/issues/294

pending https://github.com/SpoonX/spoonx-tools/pull/10

### CODE REVIEW

File: src/authentication.js [hunk 1]
```diff
@@ -291,28 +291,38 @@ export class Authentication {
...
-   * @param {[string]} defaultRedirectUrl The defaultRedirectUrl
+   * @param {string}   redirectUrl The redirect url. To not redirect use an empty string.
+   * @param {[string]} defaultRedirectUrl The defaultRedirectUrl. Used when redirectUrl is undefined
    * @param {[string]} query The optional query string to add the the url
    * @returns {undefined} undefined
    *
    * @memberOf Authentication
    */
-  redirect(redirectUrl?: string, defaultRedirectUrl?: string, query?: string) {
+  redirect(redirectUrl: string, defaultRedirectUrl?: string, query?: string) {
```
Comment (pfurini) [inline src/authentication.js:301]: @doktordirk This is a BC.. An optional parameter is now mandatory, so TS will start complaining if someone has called it without parameters.
BTW I see it was an error in the original signature, it _should_ be mandatory, so go ahead and change it..

Comment (doktordirk) [reply src/authentication.js:301]: anyways, it's an 'internal' method and calling it without just doesn't make any sense anyways 😄 

mind hitting the approve button if it's okay. makes it easier for wesley to do so as well

**Review by pfurini — APPROVED** [review]
Seems ok to me

**Review by RWOverdijk — APPROVED** [review]
